export interface Spell {
    name: string;
    description: string;
    level: number;
    classes: string[];
}

export const Spells: Spell[] = [
    { name: "Acid Splash", description: "Cantrip spell from the SRD.", level: 0, classes: ["Sorcerer", "Wizard"] },
    { name: "Chill Touch", description: "Cantrip spell from the SRD.", level: 0, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Dancing Lights", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Druidcraft", description: "Cantrip spell from the SRD.", level: 0, classes: ["Druid"] },
    { name: "Eldritch Blast", description: "Cantrip spell from the SRD.", level: 0, classes: ["Warlock"] },
    { name: "Fire Bolt", description: "Cantrip spell from the SRD.", level: 0, classes: ["Sorcerer", "Wizard"] },
    { name: "Guidance", description: "Cantrip spell from the SRD.", level: 0, classes: ["Cleric", "Druid"] },
    { name: "Light", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Cleric", "Sorcerer", "Wizard"] },
    { name: "Mage Hand", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Mending", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Wizard"] },
    { name: "Message", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Minor Illusion", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Poison Spray", description: "Cantrip spell from the SRD.", level: 0, classes: ["Druid", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Prestidigitation", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Produce Flame", description: "Cantrip spell from the SRD.", level: 0, classes: ["Druid"] },
    { name: "Ray of Frost", description: "Cantrip spell from the SRD.", level: 0, classes: ["Sorcerer", "Wizard"] },
    { name: "Resistance", description: "Cantrip spell from the SRD.", level: 0, classes: ["Cleric", "Druid"] },
    { name: "Sacred Flame", description: "Cantrip spell from the SRD.", level: 0, classes: ["Cleric"] },
    { name: "Shillelagh", description: "Cantrip spell from the SRD.", level: 0, classes: ["Druid"] },
    { name: "Shocking Grasp", description: "Cantrip spell from the SRD.", level: 0, classes: ["Sorcerer", "Wizard"] },
    { name: "Spare the Dying", description: "Cantrip spell from the SRD.", level: 0, classes: ["Cleric"] },
    { name: "Thaumaturgy", description: "Cantrip spell from the SRD.", level: 0, classes: ["Cleric"] },
    { name: "True Strike", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Vicious Mockery", description: "Cantrip spell from the SRD.", level: 0, classes: ["Bard"] },
    { name: "Alarm", description: "Level 1 spell from the SRD.", level: 1, classes: ["Ranger", "Wizard"] },
    { name: "Animal Friendship", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Druid", "Ranger"] },
    { name: "Bane", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Cleric"] },
    { name: "Bless", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Paladin"] },
    { name: "Burning Hands", description: "Level 1 spell from the SRD.", level: 1, classes: ["Sorcerer", "Wizard"] },
    { name: "Charm Person", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Druid", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Color Spray", description: "Level 1 spell from the SRD.", level: 1, classes: ["Sorcerer", "Wizard"] },
    { name: "Command", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Paladin"] },
    { name: "Comprehend Languages", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Create or Destroy Water", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Druid"] },
    { name: "Cure Wounds", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"] },
    { name: "Detect Evil and Good", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Paladin"] },
    { name: "Detect Magic", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Sorcerer", "Wizard"] },
    { name: "Detect Poison and Disease", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Druid", "Paladin", "Ranger"] },
    { name: "Disguise Self", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Divine Favor", description: "Level 1 spell from the SRD.", level: 1, classes: ["Paladin"] },
    { name: "Entangle", description: "Level 1 spell from the SRD.", level: 1, classes: ["Druid"] },
    { name: "Expeditious Retreat", description: "Level 1 spell from the SRD.", level: 1, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Faerie Fire", description: "Level 1 spell from the SRD.", level: 1, classes: ["Druid"] },
    { name: "False Life", description: "Level 1 spell from the SRD.", level: 1, classes: ["Sorcerer", "Wizard"] },
    { name: "Feather Fall", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Find Familiar", description: "Level 1 spell from the SRD.", level: 1, classes: ["Wizard"] },
    { name: "Floating Disk", description: "Level 1 spell from the SRD.", level: 1, classes: ["Wizard"] },
    { name: "Fog Cloud", description: "Level 1 spell from the SRD.", level: 1, classes: ["Druid", "Ranger", "Sorcerer", "Wizard"] },
    { name: "Goodberry", description: "Level 1 spell from the SRD.", level: 1, classes: ["Druid", "Ranger"] },
    { name: "Grease", description: "Level 1 spell from the SRD.", level: 1, classes: ["Wizard"] },
    { name: "Guiding Bolt", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric"] },
    { name: "Healing Word", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Cleric", "Druid"] },
    { name: "Hellish Rebuke", description: "Level 1 spell from the SRD.", level: 1, classes: ["Warlock"] },
    { name: "Heroism", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Paladin"] },
    { name: "Hideous Laughter", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Wizard"] },
    { name: "Hunter's Mark", description: "Level 1 spell from the SRD.", level: 1, classes: ["Ranger"] },
    { name: "Identify", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Wizard"] },
    { name: "Illusory Script", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Warlock", "Wizard"] },
    { name: "Inflict Wounds", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric"] },
    { name: "Jump", description: "Level 1 spell from the SRD.", level: 1, classes: ["Druid", "Ranger", "Sorcerer", "Wizard"] },
    { name: "Longstrider", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Druid", "Ranger", "Wizard"] },
    { name: "Mage Armor", description: "Level 1 spell from the SRD.", level: 1, classes: ["Sorcerer", "Wizard"] },
    { name: "Magic Missile", description: "Level 1 spell from the SRD.", level: 1, classes: ["Sorcerer", "Wizard"] },
    { name: "Protection from Evil and Good", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Paladin", "Warlock", "Wizard"] },
    { name: "Purify Food and Drink", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Druid", "Paladin"] },
    { name: "Sanctuary", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric"] },
    { name: "Shield", description: "Level 1 spell from the SRD.", level: 1, classes: ["Sorcerer", "Wizard"] },
    { name: "Shield of Faith", description: "Level 1 spell from the SRD.", level: 1, classes: ["Cleric", "Paladin"] },
    { name: "Silent Image", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Sleep", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Speak with Animals", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Druid", "Ranger"] },
    { name: "Thunderwave", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Druid", "Sorcerer", "Wizard"] },
    { name: "Unseen Servant", description: "Level 1 spell from the SRD.", level: 1, classes: ["Bard", "Warlock", "Wizard"] },
    { name: "Acid Arrow", description: "Level 2 spell from the SRD.", level: 2, classes: ["Wizard"] },
    { name: "Aid", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric", "Paladin"] },
    { name: "Alter Self", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Wizard"] },
    { name: "Animal Messenger", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Druid", "Ranger"] },
    { name: "Arcane Lock", description: "Level 2 spell from the SRD.", level: 2, classes: ["Wizard"] },
    { name: "Arcanist's Magic Aura", description: "Level 2 spell from the SRD.", level: 2, classes: ["Wizard"] },
    { name: "Augury", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric"] },
    { name: "Barkskin", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid", "Ranger"] },
    { name: "Blindness/Deafness", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric", "Sorcerer", "Wizard"] },
    { name: "Blur", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Wizard"] },
    { name: "Branding Smite", description: "Level 2 spell from the SRD.", level: 2, classes: ["Paladin"] },
    { name: "Calm Emotions", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric"] },
    { name: "Continual Flame", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric", "Wizard"] },
    { name: "Darkness", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Darkvision", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid", "Ranger", "Sorcerer", "Wizard"] },
    { name: "Detect Thoughts", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Enhance Ability", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric", "Druid", "Sorcerer"] },
    { name: "Enlarge/Reduce", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Wizard"] },
    { name: "Enthrall", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Warlock"] },
    { name: "Find Steed", description: "Level 2 spell from the SRD.", level: 2, classes: ["Paladin"] },
    { name: "Find Traps", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric", "Druid", "Ranger"] },
    { name: "Flame Blade", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid"] },
    { name: "Flaming Sphere", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid", "Wizard"] },
    { name: "Gentle Repose", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric", "Wizard"] },
    { name: "Gust of Wind", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Heat Metal", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Druid"] },
    { name: "Hold Person", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Invisibility", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Knock", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Lesser Restoration", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger"] },
    { name: "Levitate", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Wizard"] },
    { name: "Locate Animals or Plants", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Druid", "Ranger"] },
    { name: "Locate Object", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"] },
    { name: "Magic Mouth", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Wizard"] },
    { name: "Magic Weapon", description: "Level 2 spell from the SRD.", level: 2, classes: ["Paladin", "Wizard"] },
    { name: "Mirror Image", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Misty Step", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Moonbeam", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid"] },
    { name: "Pass Without Trace", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid", "Ranger"] },
    { name: "Prayer of Healing", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric"] },
    { name: "Protection from Poison", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric", "Druid", "Paladin", "Ranger"] },
    { name: "Ray of Enfeeblement", description: "Level 2 spell from the SRD.", level: 2, classes: ["Warlock", "Wizard"] },
    { name: "Rope Trick", description: "Level 2 spell from the SRD.", level: 2, classes: ["Wizard"] },
    { name: "Scorching Ray", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Wizard"] },
    { name: "See Invisibility", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Shatter", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Silence", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric", "Ranger"] },
    { name: "Spider Climb", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Spike Growth", description: "Level 2 spell from the SRD.", level: 2, classes: ["Druid", "Ranger"] },
    { name: "Spiritual Weapon", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric"] },
    { name: "Suggestion", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Warding Bond", description: "Level 2 spell from the SRD.", level: 2, classes: ["Cleric"] },
    { name: "Web", description: "Level 2 spell from the SRD.", level: 2, classes: ["Sorcerer", "Wizard"] },
    { name: "Zone of Truth", description: "Level 2 spell from the SRD.", level: 2, classes: ["Bard", "Cleric", "Paladin"] },
    { name: "Animate Dead", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Wizard"] },
    { name: "Beacon of Hope", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric"] },
    { name: "Bestow Curse", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Cleric", "Wizard"] },
    { name: "Blink", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Wizard"] },
    { name: "Call Lightning", description: "Level 3 spell from the SRD.", level: 3, classes: ["Druid"] },
    { name: "Clairvoyance", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Cleric", "Sorcerer", "Wizard"] },
    { name: "Conjure Animals", description: "Level 3 spell from the SRD.", level: 3, classes: ["Druid", "Ranger"] },
    { name: "Counterspell", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Create Food and Water", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Druid", "Paladin"] },
    { name: "Daylight", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Druid", "Paladin", "Ranger", "Sorcerer"] },
    { name: "Dispel Magic", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Cleric", "Druid", "Paladin", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Fear", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Fireball", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Wizard"] },
    { name: "Fly", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Gaseous Form", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Glyph of Warding", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Cleric", "Wizard"] },
    { name: "Haste", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Wizard"] },
    { name: "Hypnotic Pattern", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Lightning Bolt", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Wizard"] },
    { name: "Magic Circle", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Paladin", "Warlock", "Wizard"] },
    { name: "Major Image", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Mass Healing Word", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric"] },
    { name: "Meld Into Stone", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric"] },
    { name: "Nondetection", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Ranger", "Wizard"] },
    { name: "Phantom Steed", description: "Level 3 spell from the SRD.", level: 3, classes: ["Wizard"] },
    { name: "Plant Growth", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Druid", "Ranger"] },
    { name: "Protection From Energy", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Druid", "Ranger", "Sorcerer", "Wizard"] },
    { name: "Remove Curse", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Paladin", "Warlock", "Wizard"] },
    { name: "Revivify", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Paladin"] },
    { name: "Sending", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Cleric", "Wizard"] },
    { name: "Sleet Storm", description: "Level 3 spell from the SRD.", level: 3, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Slow", description: "Level 3 spell from the SRD.", level: 3, classes: ["Sorcerer", "Wizard"] },
    { name: "Speak with Dead", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Cleric"] },
    { name: "Speak with Plants", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Druid", "Ranger"] },
    { name: "Spirit Guardians", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric"] },
    { name: "Stinking Cloud", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Tiny Hut", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Wizard"] },
    { name: "Tongues", description: "Level 3 spell from the SRD.", level: 3, classes: ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Vampiric Touch", description: "Level 3 spell from the SRD.", level: 3, classes: ["Warlock", "Wizard"] },
    { name: "Water Breathing", description: "Level 3 spell from the SRD.", level: 3, classes: ["Druid", "Ranger", "Sorcerer", "Wizard"] },
    { name: "Water Walk", description: "Level 3 spell from the SRD.", level: 3, classes: ["Cleric", "Druid", "Ranger", "Sorcerer"] },
    { name: "Wind Wall", description: "Level 3 spell from the SRD.", level: 3, classes: ["Druid", "Ranger"] },
    { name: "Arcane Eye", description: "Level 4 spell from the SRD.", level: 4, classes: ["Cleric", "Wizard"] },
    { name: "Banishment", description: "Level 4 spell from the SRD.", level: 4, classes: ["Cleric", "Paladin", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Black Tentacles", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Blight", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Compulsion", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard"] },
    { name: "Confusion", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard", "Druid", "Sorcerer", "Wizard"] },
    { name: "Conjure Minor Elementals", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid", "Wizard"] },
    { name: "Conjure Woodland Beings", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid", "Ranger"] },
    { name: "Control Water", description: "Level 4 spell from the SRD.", level: 4, classes: ["Cleric", "Druid", "Wizard"] },
    { name: "Death Ward", description: "Level 4 spell from the SRD.", level: 4, classes: ["Cleric", "Paladin"] },
    { name: "Dimension Door", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Divination", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid"] },
    { name: "Dominate Beast", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid", "Sorcerer"] },
    { name: "Fabricate", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Faithful Hound", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Fire Shield", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Freedom of Movement", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard", "Cleric", "Druid", "Ranger"] },
    { name: "Giant Insect", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid"] },
    { name: "Greater Invisibility", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Guardian of Faith", description: "Level 4 spell from the SRD.", level: 4, classes: ["Cleric"] },
    { name: "Hallucinatory Terrain", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard", "Druid", "Warlock", "Wizard"] },
    { name: "Ice Storm", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Locate Creature", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard", "Cleric", "Druid", "Paladin", "Ranger", "Wizard"] },
    { name: "Phantasmal Killer", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Polymorph", description: "Level 4 spell from the SRD.", level: 4, classes: ["Bard", "Druid", "Sorcerer", "Wizard"] },
    { name: "Private Sanctum", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Resilient Sphere", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Secret Chest", description: "Level 4 spell from the SRD.", level: 4, classes: ["Wizard"] },
    { name: "Stone Shape", description: "Level 4 spell from the SRD.", level: 4, classes: ["Cleric", "Druid", "Wizard"] },
    { name: "Stoneskin", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid", "Ranger", "Sorcerer", "Wizard"] },
    { name: "Wall of Fire", description: "Level 4 spell from the SRD.", level: 4, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Animate Objects", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Antilife Shell", description: "Level 5 spell from the SRD.", level: 5, classes: ["Druid"] },
    { name: "Arcane Hand", description: "Level 5 spell from the SRD.", level: 5, classes: ["Wizard"] },
    { name: "Awaken", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Druid"] },
    { name: "Cloudkill", description: "Level 5 spell from the SRD.", level: 5, classes: ["Sorcerer", "Wizard"] },
    { name: "Commune", description: "Level 5 spell from the SRD.", level: 5, classes: ["Cleric"] },
    { name: "Commune With Nature", description: "Level 5 spell from the SRD.", level: 5, classes: ["Druid", "Ranger"] },
    { name: "Cone of Cold", description: "Level 5 spell from the SRD.", level: 5, classes: ["Sorcerer", "Wizard"] },
    { name: "Conjure Elemental", description: "Level 5 spell from the SRD.", level: 5, classes: ["Druid", "Wizard"] },
    { name: "Contact Other Plane", description: "Level 5 spell from the SRD.", level: 5, classes: ["Warlock", "Wizard"] },
    { name: "Contagion", description: "Level 5 spell from the SRD.", level: 5, classes: ["Cleric", "Druid"] },
    { name: "Creation", description: "Level 5 spell from the SRD.", level: 5, classes: ["Sorcerer", "Wizard"] },
    { name: "Dispel Evil and Good", description: "Level 5 spell from the SRD.", level: 5, classes: ["Cleric", "Paladin"] },
    { name: "Dominate Person", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Dream", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Warlock", "Wizard"] },
    { name: "Flame Strike", description: "Level 5 spell from the SRD.", level: 5, classes: ["Cleric"] },
    { name: "Geas", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Cleric", "Druid", "Paladin", "Wizard"] },
    { name: "Greater Restoration", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Cleric", "Druid"] },
    { name: "Hallow", description: "Level 5 spell from the SRD.", level: 5, classes: ["Cleric"] },
    { name: "Hold Monster", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Insect Plague", description: "Level 5 spell from the SRD.", level: 5, classes: ["Cleric", "Druid", "Sorcerer"] },
    { name: "Legend Lore", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Cleric", "Wizard"] },
    { name: "Mass Cure Wounds", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Cleric", "Druid"] },
    { name: "Mislead", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Wizard"] },
    { name: "Modify Memory", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Wizard"] },
    { name: "Passwall", description: "Level 5 spell from the SRD.", level: 5, classes: ["Wizard"] },
    { name: "Planar Binding", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Cleric", "Druid", "Wizard"] },
    { name: "Raise Dead", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Cleric", "Paladin"] },
    { name: "Reincarnate", description: "Level 5 spell from the SRD.", level: 5, classes: ["Druid"] },
    { name: "Scrying", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Cleric", "Druid", "Warlock", "Wizard"] },
    { name: "Seeming", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Telekinesis", description: "Level 5 spell from the SRD.", level: 5, classes: ["Sorcerer", "Wizard"] },
    { name: "Telepathic Bond", description: "Level 5 spell from the SRD.", level: 5, classes: ["Wizard"] },
    { name: "Teleportation Circle", description: "Level 5 spell from the SRD.", level: 5, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Tree Stride", description: "Level 5 spell from the SRD.", level: 5, classes: ["Druid", "Ranger"] },
    { name: "Wall of Force", description: "Level 5 spell from the SRD.", level: 5, classes: ["Wizard"] },
    { name: "Wall of Stone", description: "Level 5 spell from the SRD.", level: 5, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Blade Barrier", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric"] },
    { name: "Chain Lightning", description: "Level 6 spell from the SRD.", level: 6, classes: ["Sorcerer", "Wizard"] },
    { name: "Circle of Death", description: "Level 6 spell from the SRD.", level: 6, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Conjure Fey", description: "Level 6 spell from the SRD.", level: 6, classes: ["Druid", "Warlock"] },
    { name: "Contingency", description: "Level 6 spell from the SRD.", level: 6, classes: ["Wizard"] },
    { name: "Create Undead", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric", "Warlock", "Wizard"] },
    { name: "Disintegrate", description: "Level 6 spell from the SRD.", level: 6, classes: ["Sorcerer", "Wizard"] },
    { name: "Eyebite", description: "Level 6 spell from the SRD.", level: 6, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Find the Path", description: "Level 6 spell from the SRD.", level: 6, classes: ["Bard", "Cleric", "Druid"] },
    { name: "Flesh to Stone", description: "Level 6 spell from the SRD.", level: 6, classes: ["Warlock", "Wizard"] },
    { name: "Forbiddance", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric"] },
    { name: "Freezing Sphere", description: "Level 6 spell from the SRD.", level: 6, classes: ["Wizard"] },
    { name: "Globe of Invulnerability", description: "Level 6 spell from the SRD.", level: 6, classes: ["Sorcerer", "Wizard"] },
    { name: "Guards and Wards", description: "Level 6 spell from the SRD.", level: 6, classes: ["Bard", "Wizard"] },
    { name: "Harm", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric"] },
    { name: "Heal", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric", "Druid"] },
    { name: "Heroes' Feast", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric", "Druid"] },
    { name: "Instant Summons", description: "Level 6 spell from the SRD.", level: 6, classes: ["Wizard"] },
    { name: "Irresistible Dance", description: "Level 6 spell from the SRD.", level: 6, classes: ["Bard", "Wizard"] },
    { name: "Magic Jar", description: "Level 6 spell from the SRD.", level: 6, classes: ["Wizard"] },
    { name: "Mass Suggestion", description: "Level 6 spell from the SRD.", level: 6, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Move Earth", description: "Level 6 spell from the SRD.", level: 6, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Planar Ally", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric"] },
    { name: "Programmed Illusion", description: "Level 6 spell from the SRD.", level: 6, classes: ["Bard", "Wizard"] },
    { name: "Sunbeam", description: "Level 6 spell from the SRD.", level: 6, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Transport via Plants", description: "Level 6 spell from the SRD.", level: 6, classes: ["Druid"] },
    { name: "True Seeing", description: "Level 6 spell from the SRD.", level: 6, classes: ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Wall of Ice", description: "Level 6 spell from the SRD.", level: 6, classes: ["Wizard"] },
    { name: "Wall of Thorns", description: "Level 6 spell from the SRD.", level: 6, classes: ["Druid"] },
    { name: "Wind Walk", description: "Level 6 spell from the SRD.", level: 6, classes: ["Druid"] },
    { name: "Word of Recall", description: "Level 6 spell from the SRD.", level: 6, classes: ["Cleric"] },
    { name: "Arcane Sword", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Wizard"] },
    { name: "Conjure Celestial", description: "Level 7 spell from the SRD.", level: 7, classes: ["Cleric"] },
    { name: "Delayed Blast Fireball", description: "Level 7 spell from the SRD.", level: 7, classes: ["Sorcerer", "Wizard"] },
    { name: "Divine Word", description: "Level 7 spell from the SRD.", level: 7, classes: ["Cleric"] },
    { name: "Etherealness", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Cleric", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Finger of Death", description: "Level 7 spell from the SRD.", level: 7, classes: ["Sorcerer", "Warlock", "Wizard"] },
    { name: "Fire Storm", description: "Level 7 spell from the SRD.", level: 7, classes: ["Cleric", "Druid", "Sorcerer"] },
    { name: "Forcecage", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Warlock", "Wizard"] },
    { name: "Magnificent Mansion", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Wizard"] },
    { name: "Mirage Arcane", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Druid", "Wizard"] },
    { name: "Plane Shift", description: "Level 7 spell from the SRD.", level: 7, classes: ["Cleric", "Druid", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Prismatic Spray", description: "Level 7 spell from the SRD.", level: 7, classes: ["Sorcerer", "Wizard"] },
    { name: "Project Image", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Wizard"] },
    { name: "Regenerate", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Cleric", "Druid"] },
    { name: "Resurrection", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Cleric"] },
    { name: "Reverse Gravity", description: "Level 7 spell from the SRD.", level: 7, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Sequester", description: "Level 7 spell from the SRD.", level: 7, classes: ["Wizard"] },
    { name: "Simulacrum", description: "Level 7 spell from the SRD.", level: 7, classes: ["Wizard"] },
    { name: "Symbol", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Cleric", "Wizard"] },
    { name: "Teleport", description: "Level 7 spell from the SRD.", level: 7, classes: ["Bard", "Sorcerer", "Wizard"] },
    { name: "Animal Shapes", description: "Level 8 spell from the SRD.", level: 8, classes: ["Druid"] },
    { name: "Antimagic Field", description: "Level 8 spell from the SRD.", level: 8, classes: ["Cleric", "Wizard"] },
    { name: "Antipathy/Sympathy", description: "Level 8 spell from the SRD.", level: 8, classes: ["Druid", "Wizard"] },
    { name: "Clone", description: "Level 8 spell from the SRD.", level: 8, classes: ["Wizard"] },
    { name: "Control Weather", description: "Level 8 spell from the SRD.", level: 8, classes: ["Cleric", "Druid", "Wizard"] },
    { name: "Demiplane", description: "Level 8 spell from the SRD.", level: 8, classes: ["Warlock", "Wizard"] },
    { name: "Dominate Monster", description: "Level 8 spell from the SRD.", level: 8, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Earthquake", description: "Level 8 spell from the SRD.", level: 8, classes: ["Cleric", "Druid", "Sorcerer"] },
    { name: "Feeblemind", description: "Level 8 spell from the SRD.", level: 8, classes: ["Bard", "Druid", "Warlock", "Wizard"] },
    { name: "Glibness", description: "Level 8 spell from the SRD.", level: 8, classes: ["Bard", "Warlock"] },
    { name: "Holy Aura", description: "Level 8 spell from the SRD.", level: 8, classes: ["Cleric"] },
    { name: "Incendiary Cloud", description: "Level 8 spell from the SRD.", level: 8, classes: ["Sorcerer", "Wizard"] },
    { name: "Maze", description: "Level 8 spell from the SRD.", level: 8, classes: ["Wizard"] },
    { name: "Mind Blank", description: "Level 8 spell from the SRD.", level: 8, classes: ["Bard", "Wizard"] },
    { name: "Power Word Stun", description: "Level 8 spell from the SRD.", level: 8, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Sunburst", description: "Level 8 spell from the SRD.", level: 8, classes: ["Druid", "Sorcerer", "Wizard"] },
    { name: "Astral Projection", description: "Level 9 spell from the SRD.", level: 9, classes: ["Cleric", "Warlock", "Wizard"] },
    { name: "Foresight", description: "Level 9 spell from the SRD.", level: 9, classes: ["Bard", "Druid", "Warlock", "Wizard"] },
    { name: "Gate", description: "Level 9 spell from the SRD.", level: 9, classes: ["Cleric", "Sorcerer", "Wizard"] },
    { name: "Imprisonment", description: "Level 9 spell from the SRD.", level: 9, classes: ["Warlock", "Wizard"] },
    { name: "Mass Heal", description: "Level 9 spell from the SRD.", level: 9, classes: ["Cleric"] },
    { name: "Meteor Swarm", description: "Level 9 spell from the SRD.", level: 9, classes: ["Sorcerer", "Wizard"] },
    { name: "Power Word Kill", description: "Level 9 spell from the SRD.", level: 9, classes: ["Bard", "Sorcerer", "Warlock", "Wizard"] },
    { name: "Prismatic Wall", description: "Level 9 spell from the SRD.", level: 9, classes: ["Wizard"] },
    { name: "Shapechange", description: "Level 9 spell from the SRD.", level: 9, classes: ["Druid", "Wizard"] },
    { name: "Storm of Vengeance", description: "Level 9 spell from the SRD.", level: 9, classes: ["Druid"] },
    { name: "Time Stop", description: "Level 9 spell from the SRD.", level: 9, classes: ["Sorcerer", "Wizard"] },
    { name: "True Polymorph", description: "Level 9 spell from the SRD.", level: 9, classes: ["Bard", "Warlock", "Wizard"] },
    { name: "True Resurrection", description: "Level 9 spell from the SRD.", level: 9, classes: ["Cleric", "Druid"] },
    { name: "Weird", description: "Level 9 spell from the SRD.", level: 9, classes: ["Wizard"] },
    { name: "Wish", description: "Level 9 spell from the SRD.", level: 9, classes: ["Sorcerer", "Wizard"] },
];

export function GetSpellByName(name: string): Spell | undefined {
    return Spells.find(spell => spell.name.toLowerCase() === name.toLowerCase());
}

export function GetSpellsByClass(className: string): Spell[] {
    return Spells.filter(spell => spell.classes.some(c => c.toLowerCase() === className.toLowerCase()));
}
